/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <string>
#include <stdlib.h>
#include "app.h"

std::string LearnCpp::Greeter::greeting() {
    return std::string("Hello, World!");
}

class Test {
public:
    Test() {
        name_ = "Daiwei";
    }

    const std::string& getName() {
        // std::cout << &name_ << std::endl;
        return name_;
    }

    void setName(std::string name) {
        name_ = name;
    }

private:
    std::string name_;
};

class Say {
public:
    Say(const std::string& name): name_(std::move(name)) {
        // std::cout << &name << std::endl;
        // std::cout << &name_ << std::endl;
    }

    void sayName() {
        std::cout << "Hello " << name_ << std::endl;
    }

private:
    std::string name_;
};

int main () {
    std::cout << __cplusplus << std::endl;

    Test t;
    const std::string name = t.getName();
    // std::cout << &name << std::endl;
    // Say s(name);

    // s.sayName();

    // std::cout << t.getName() << std::endl;

    std::cout << name << std::endl;

    // t.setName("Anqi");

    // std::cout << t.getName() << std::endl;

    // s.sayName();

    return 0;
}
